# Generated by Django 4.2.1 on 2023-06-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volume', '0003_pin_likes_pin_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='price',
        ),
    ]
