# Generated by Django 4.2.1 on 2023-06-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volume', '0004_remove_pin_likes_remove_pin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
