# Generated by Django 4.2.1 on 2023-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volume', '0005_pin_likes_pin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_pins',
            field=models.ManyToManyField(related_name='liked_users', to='Volume.pin'),
        ),
    ]
